"""Add github_username to users table

Revision ID: 622358f54d5d
Revises: fcbc4f99cefd
Create Date: 2025-07-30 15:21:14.743682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622358f54d5d'
down_revision: Union[str, Sequence[str], None] = 'fcbc4f99cefd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_username', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['github_username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'github_username')
    # ### end Alembic commands ###
