"""Add project_type and project_detection_confidence to conversations

Revision ID: e6399ae08c60
Revises: c34170339a9d
Create Date: 2025-08-04 15:00:31.473593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6399ae08c60'
down_revision: Union[str, Sequence[str], None] = 'c34170339a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('project_type', sa.String(length=50), nullable=True))
    op.add_column('conversations', sa.Column('project_detection_confidence', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_csrf_tokens_token'), table_name='csrf_tokens')
    op.create_index(op.f('ix_csrf_tokens_token'), 'csrf_tokens', ['token'], unique=True)
    op.alter_column('llm_configurations', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('llm_configurations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('llm_configurations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('llm_configurations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_sessions_token_hash'), table_name='sessions')
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.create_index(op.f('idx_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.alter_column('llm_configurations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('llm_configurations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('llm_configurations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('llm_configurations', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_csrf_tokens_token'), table_name='csrf_tokens')
    op.create_index(op.f('idx_csrf_tokens_token'), 'csrf_tokens', ['token'], unique=True)
    op.drop_column('conversations', 'project_detection_confidence')
    op.drop_column('conversations', 'project_type')
    # ### end Alembic commands ###
